### PR TITLE
README: move to upstream yocto meta-lts-mixins

### PR DESCRIPTION
**Pull request by quaresmajose**
When merged this repository can be archived.

### CODE REVIEW

**Comment by doanac** [comment]
> When merged this repository can be archived.

are there older LmP versions using this? i.e. do we have to wait until all customers update?

**Comment by quaresmajose** [comment]
> > When merged this repository can be archived.
> 
> are there older LmP versions using this? i.e. do we have to wait until all customers update?

No, this repo was introduced during the development of the version v90 so I think none of ours customers have it.
With https://github.com/foundriesio/lmp-manifest/pull/313 it is not need anymore.

**Review by doanac — APPROVED** [review]
David or I can delete this once you are ready. Not sure we need a PR for this.

**Comment by ricardosalveti** [comment]
> David or I can delete this once you are ready. Not sure we need a PR for this.

Safe to delete anytime.

**Pull request merged**
